name: CI

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@master
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'beta'

      - name: install
        run: |
          flutter upgrade
          flutter config --enable-web
          flutter pub get

      - name: build
        run: flutter build web

      - name: deploy(github-page)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
          publish_dir: ./build/web

      - name: deploy(firebase-hosting)
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.DEPLOY_TOKEN_FIREBASE }}

